sudo: false
language: rust
cache: cargo

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libssl-dev
    - binutils-dev

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly
  - rust: beta

before_script:
- export PATH=$HOME/.cargo/bin:$PATH
- which cargo-tarpaulin || cargo install cargo-tarpaulin
- which cargo-install-update || cargo install cargo-update
- cargo install-update -a

script:
- cargo test --all
- cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
